services:

  recommendation-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /recommendation-service/.venv
      - .:/recommendation-service
    tty: true
    networks:
      - recommendation-service
      - backend
      - analytics
    labels:
      - "traefik.http.routers.recommendation-service.rule=HostRegexp(`api\\..+`) && PathPrefix(`/recommendation`)"

networks:
  recommendation-service:


