services:
  recommendation-service:
    build:
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      REDIS_HOST: recommendation-service_redis
    depends_on:
      recommendation-service_redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    tty: true
    networks:
      - recommendation-service
      - backend
      - analytics
    env_file:
      - .env

networks:
  recommendation-service:
