[project]
name = "recommendation-service"
version = "0.1.0"
description = ""
authors = [
    { name = "andre", email = "andrepedro2004@hotmail.com" }
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "fastapi (>=0.115.11,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "apache-airflow (>=2.10.5,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",    
    "redis (>=5.2.1,<6.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "torch (>=2.6.0,<3.0.0)",
    "sentence-transformers (>=4.0.2,<5.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "optuna (>=4.2.1,<5.0.0)",
    "qdrant-client (>=1.13.3,<2.0.0)",
    "hnswlib (>=0.8.0,<0.9.0)",
    "airflow-providers (>=0.3.0,<0.4.0)",
    "apache-airflow-providers-postgres (>=6.1.2,<7.0.0)",
    "apache-airflow-providers-redis (>=4.0.2,<5.0.0)",
    "apache-airflow-providers-mongo (>=5.0.2,<6.0.0)",
]

[tool.poetry]
package-mode = false




[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.25.3"
black = "^25.1.0"
isort = "^6.0.1"
watchfiles = "^1.0.4"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
